---

- include: security.yml

- name: "log folder for {{app_install_dir}}"
  file:
    path: /var/log/{{dseg_user_name}}
    state: directory
    owner: "{{dseg_user_name}}"
    group: "{{dseg_group_name}}"

- name: "Set ownership of {{app_install_dir}} directory"
  file:
    path: /usr/local/{{app_install_dir}}
    state: directory
    owner: "{{dseg_user_name}}"
    group: "{{dseg_group_name}}"
    mode: 0755
    recurse: yes

- include: install-dseg.yml

- include: upstart.yml

- include: consul-health.yml

