---
- name: "Add {{dseg_group_name}} group"
  group: name={{dseg_group_name}} system=yes

- name: "Add {{dseg_user_name}} user"
  user:
    name: "{{dseg_user_name}}"
    group: "{{dseg_group_name}}"
    system: yes

- pam_limits: domain=* limit_type=- limit_item=nofile value=128000
- pam_limits: domain=* limit_type=- limit_item=nproc value=64000
